spring.application.name=eureka-server

server.port=8761

# ACTUATOR
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Service Registry for Order Management System

# This application is the Eureka Server,
# so it should not register itself.
eureka.client.register-with-eureka=false

# Standalone Eureka Server does not need
# to fetch another Eureka registry.
eureka.client.fetch-registry=false

# Optional: reduce Eureka console logs.
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
